#!/bin/bash

echo DOWNLOAD ZIP:
wget -O raspbian-lite.zip http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-04-19/2018-04-18-raspbian-stretch-lite.zip

echo SHA1SUM:
sha1sum raspbian-lite.zip

echo UNZIP:
unzip -o raspbian-lite.zip
original_img=$(ls | grep 20*raspbian*.img)
mv $original_img raspbian-lite.img

echo CLEAN:
rm -rf raspbian-lite.zip
