#!/bin/bash

docker build -t alxprd/raspbian-image-explorer-stretch-lite -f docker/Dockerfile.stretch-lite ./docker
docker build -t alxprd/raspbian-image-explorer-stretch-desktop -f docker/Dockerfile.stretch-desktop ./docker
