#!/bin/bash

# Source1: https://learnaddict.com/2016/02/23/modifying-a-raspberry-pi-raspbian-image-on-linux/
# Source2: https://unix.stackexchange.com/questions/342463/mount-multiple-partitions-from-disk-image-simultaneously#342466
# Source3: https://linux.die.net/man/8/mount
# Source4: https://linux.die.net/man/8/losetup

# Extra: https://coderwall.com/p/quflrg/run-a-script-on-startup-in-a-detached-screen-on-a-raspberry-pi

echo STARTING...

if [ ! -f raspbian.zip ]; then
    echo DOWNLOAD ZIP:
    wget -O raspbian.zip http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-04-19/2018-04-18-raspbian-stretch-lite.zip

    echo SHA1SUM:
    sha1sum raspbian.zip
fi

if [ ! -f raspbian.img ]; then
    echo UNZIP:
    unzip -o raspbian.zip
    original_img=$(ls | grep 20*raspbian*.img)
    mv $original_img raspbian.img
fi

echo FDISK:
fdisk -l raspbian.img

echo MOUNT BOOT:
echo "start:"
read offset_boot
echo "sectors:"
read size_boot
mkdir -p /mnt/image/boot
mount -v -o offset=$(($offset_boot*512)),sizelimit=$(($size_boot*512)) -t vfat raspbian.img /mnt/image/boot
ls /mnt/image/boot

echo MOUNT FILESYSTEM:
echo "start:"
read offset_filesystem
echo "sectors:"
read size_filesystem
mkdir -p /mnt/image/filesystem
mount -v -o offset=$(($offset_filesystem*512)),sizelimit=$(($size_filesystem*512)) -t ext4 raspbian.img /mnt/image/filesystem
ls /mnt/image/filesystem


# Do things ...


#echo UMOUNT:
#umount /mnt/image/boot
#umount /mnt/image/filesystem 
